### ISSUE TITLE
How to send metadata using Payment Intent

### ISSUE THREAD

**Issue by ajithv11** [stripe/stripe-terminal-js-demo#105]
I have manually tried to add metadata to `createPaymentIntent` function as given below

 createPaymentIntent({ amount, currency, description, metadata, paymentMethodTypes }) {
      const formData = new URLSearchParams();
      formData.append("amount", amount);
      formData.append("currency", currency);
      formData.append("description", description);
      formData.append(`metadata[myId]`, "123456");
      paymentMethodTypes.forEach((type) => formData.append(`payment_method_types[]`, type));
      return this.doPost(this.url + "/create_payment_intent", formData);
    }

But the above method did'nt send `myId` to the stripe , Could you please help me to fix this. I need to add more metadata along with this

Thanks in advance

**Comment by jdivock-stripe** [comment]
Hey @ajithv11 any changes to the stripe demo app would have to be paired with your backend forwarding that metadata to stripe. We have further docs here https://stripe.com/docs/payments/payment-intents#storing-information-in-metadata and i if you still require assistance I'd reach out to our developer assistance team on discord. Thanks!
