### ISSUE TITLE
Implement in Typesciprt

### ISSUE THREAD

**Issue by jatinb92** [stripe/stripe-terminal-js-demo#86]
How to implement the same js functionality of fetchingConnection while initializing javascript SDK from ANGULAR application - typescript file.

**Comment by jdivock-stripe** [comment]
I'm sorry, is this a bug report?

**Comment by jdivock-stripe** [comment]
Going to go ahead and close this one out as it doesn't relate to the repo. If you continue to have issues with your integration feel free to reach out via https://support.stripe.com/email or come chat live with our developers at https://stripe.com/go/developer-chat
